### ISSUE TITLE
Return file instead of path

### ISSUE THREAD

**Issue by kamami** [TenkaiRuri/flutter_video_compress#11]
Hi,
I need to upload the compressed video to firebase.
 Any possability to return the compressed file instead of the path? 

Good job btw. with the widget!

**Comment by TenkaiRuri** [comment]
If you want to convert path to file you can refer to the example.
```dart
final CompressResult result = await _flutterVideoCompress
  .startCompress(path: file.path, deleteOrigin: true);

final _file = File(result.path);
```
Thank you for your suggestion, I will enhance it in the next version.

**Comment by kamami** [comment]
@TenkaiRuri I tried that before but its not working:

> Error uploading image to storage : 'package:firebase_storage/src/storage_reference.dart': Failed assertion: line 62 pos 12: 'file.existsSync()': is not true.

Uploading the original file with the same function is working fine.

**Comment by kamami** [comment]
It is only working when capturing the video by camera. Picking it from the galley throws the error I wrote in my comment above...

**Comment by febg11** [comment]
I think I had this.. Try copying the file from the path returned to the users temp directory on the phone. It should be able to access it then.

**Comment by kamami** [comment]
@febg11 could you show how you did that? Would appreciate!

**Comment by TenkaiRuri** [comment]
Have you checked the files in the path that exist in the file manager application, I want to know this information for reference.

**Comment by kamami** [comment]
@kamami I like to help, but you need to explain more in detail which information you need. I am quite new to flutter!

**Comment by febg11** [comment]
Sorry @kamami I misread what you put. I think your issue is different to my suggestion.

**Comment by TenkaiRuri** [comment]
I have enhanced this feature, now you can try it.
If you have any questions, please open this question again.
Thank you for the issue

**Comment by nthungdev** [comment]
I am having the issue that @kamami  was having. Is there a fix for that problem?
