### ISSUE TITLE
Return image or file insteaf of uint8list

### ISSUE THREAD

**Issue by kamami** [TenkaiRuri/flutter_video_compress#12]
Is there a way to return the thumbnail as an image or a file? I cannot convert the uint8list back to an image...

Kind Regards

**Comment by Torlinone** [comment]
`Image.memory(
Uint8List bytes)`
please checkout [Image](https://api.flutter.dev/flutter/widgets/Image-class.html)

**Comment by kamami** [comment]
@Torlinone I need to get the image as a file to upload it to firebase. Thats why I am asking for an image instead of an Uint8List.

**Comment by kamami** [comment]
I found a method `_storageReferenceThumb.putData` from flutter firebase. It allows to upload Uint8List :) So nvm!

**Comment by TenkaiRuri** [comment]
I have enhanced this feature, now you can try it.
If you have any questions, please open this question again.
Thank you for the issue
