### ISSUE TITLE
 Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by kamami** [TenkaiRuri/flutter_video_compress#15]
When popping the page (example page of the project) and returning following error is thrown:

>  Bad state: Stream has already been listened to.

```
  @override
  void dispose() {
    super.dispose();
    _subscription.unsubscribe();
  }
```
Dispose is implemented.

**Comment by TenkaiRuri** [comment]
can you provide a minimal repo?

**Comment by kamami** [comment]
https://github.com/kamami/Compress.git

**Comment by TenkaiRuri** [comment]
@kamai I suggest deleting other commit records, by using the following command, or by directly deleting repo.
```bash
git rm -r --cached .
git update-ref -d HEAD
git add .
git commit -m "first commit"
git push -u -f origin master
```

**Comment by TenkaiRuri** [comment]
When constructor flutter_video_compress, will take from the cache. Now I remove it.
