### ISSUE TITLE
compressed video is null

### ISSUE THREAD

**Issue by kamami** [TenkaiRuri/flutter_video_compress#16]
I am trying to compress a video file and return the new compressed file, but following code prints NULL both times:

       final MediaInfo newPath = await _flutterVideoCompress.startCompress(
        widget.videoFile.path,
        deleteOrigin: true,
      );

      setState(() {
        video = newPath.file;
      });

       print("${newPath.file}");
       print("$video");

**Comment by TenkaiRuri** [comment]
Is this question related to the overlay file mentioned in #14?

**Comment by kamami** [comment]
@TenkaiRuri no it is an independet issue I found while testing. Does not work whether recording a video or picking one from the gallery.

**Comment by kamami** [comment]
This minimal repo is working for me and shows the issue:

https://github.com/kamami/Compress.git

**Comment by TenkaiRuri** [comment]
I forgot model definition 😂
