### ISSUE TITLE
[Feature] Create GIF output as video thumbnail

### ISSUE THREAD

**Issue by lecicdjuro** [TenkaiRuri/flutter_video_compress#18]
Is there any possibility to create gif output for video thumbnail?

**Comment by TenkaiRuri** [comment]
I don't have an idea to resolve the time range of cropping.

**Comment by lecicdjuro** [comment]
I think that gif should start from mediaInfo.duration / 3 up top next 2 or 3 seconds and method should be getVideoThumbnailAsGifFile(String videoPath)
Is it possible?

**Comment by TenkaiRuri** [comment]
@lecicdjuro Thanks for your feedback.

I think it will solve this bill with problems
```dart
Future<File> saveToGif(String path, {
  int startTime, 
  int endTime,
  int cutSec,  // When you do not know the end time
})
```
> gif should start from mediaInfo.duration / 3 up top next 2 or 3 seconds

The default parameters will be adopted in your way

**Usage**
```dart
File = await saveToGif(path)
```

If you agree with the idea, it will be updated in the next release.

**Comment by lecicdjuro** [comment]
Perfect. Thanks a lot! 
When do you plan to release the next version?

**Comment by TenkaiRuri** [comment]
This weekend 🤔

**Comment by vlada3003** [comment]
Hey @TenkaiRuri sorry to drop in like this, but I am @lecicdjuro's colleague and I had some spare time so I actually implemented the feature. However, I cannot open a pull request on your git, nor can I push a code change to a branch. Can you please add me so I can get the change up on for review if that is ok with you?

**Comment by vlada3003** [comment]
Thanks! Can you please take a look when you get a chance?
Please note that I'm an Android developer and don't have any experience in Flutter nor in iOS and Swift so when review please take a special look at that part of the code.
Also, I have taken the liberty to refactor Kotlin code since the single class where everything was located was  getting too big so I have just broken it into several smaller classes instead to improve readability.

**Comment by TenkaiRuri** [comment]
@vlada3003 
Tbh, I am also a beginner. Neither swift nor kotlin have been formally written.
All code is written in google search. I am originally a front end developer.
Maybe this is why my code is bad :)

Thank you for the pull request. I am very happy now, the language can't express my happiness. .

Rumi Amami

**Comment by vlada3003** [comment]
thanks. when will you upload the next version to the repo?

**Comment by TenkaiRuri** [comment]
@vlada3003 Already, I modified some document comments so that dart can better support.
