### ISSUE TITLE
PlatformException(flutter_video_compress, 8, 8)

### ISSUE THREAD

**Issue by Maliffic** [TenkaiRuri/flutter_video_compress#2]
I/PLDroidShortVideo( 7999): Pili-Transcode:ShortVideoTranscoderCore:init -
I/PLDroidShortVideo( 7999): Pili-Transcode:ShortVideoTranscoderCore:transcode +
E/PLDroidShortVideo( 7999): Pili-System:ZeusManager:no authorized feature : transcode_video status : UnAuthorized
I/flutter ( 7999): FlutterVideoCompress Error:
I/flutter ( 7999):       Method: compressVideo
I/flutter ( 7999):       PlatformException(flutter_video_compress, 8, 8)

I find it works now and then , then this error starts happening

**Comment by TenkaiRuri** [comment]
I have changed the implementation behind, and i tested on the platform and passed, now it's haven't error of the code 8. if you have other problems, please open this issue again, thank you.
