### ISSUE TITLE
[Bug] Failed to ensure /storage/~/files/flutter_video_compress: 400

### ISSUE THREAD

**Issue by GustavoContreiras** [TenkaiRuri/flutter_video_compress#22]
### Platform
Android

### Backtracking step (if has)
  1. open application
  2. get video file from gallery with image picker
  3. start compress file with flutter video compress

```
D/FFmpeg  (29290): Build.CPU_ABI : armeabi-v7a
D/FFmpeg  (29290): ffmpeg is ready!
W/ContextImpl(29290): Failed to ensure /storage/~/files/flutter_video_compress: 400
D/FFmpeg  (29290): Running publishing updates method
```

Why am I getting this?
Also compressing is taking forever.

**Comment by GustavoContreiras** [comment]
> 
> 
> > Also compressing is taking forever.
> 
> You can try subscription the compressing state.
> 
> ```dart
> _subscription =  _flutterVideoCompress.compressProgress$.subscribe((progress) {
>   print('progress: $progress');
> });
> ```
> 
> > W/ContextImpl(29290): Failed to ensure /storage/3AA1-1B06/Android/data/com.beta2.wavecheck/files/flutter_video_compress: 400
> 
> There are two possibilities for this
> 
>     1. Look for a [detailed explanation ](https://stackoverflow.com/questions/33362620/android-failed-to-ensure-directory#answer-41262228) of this issue.
> 
>     2. You may have disabled the SD card.

Thanks. It's probably my SD card. I'm having problems with download and moving Spotify music files to the SD card and their support told me to test another SD card on my device (and I didn't do it lol).

Anyway, even taking a lot of time I could do the compress.

**Comment by TenkaiRuri** [comment]
Refer to the code
```dart
final info = await _flutterVideoCompress.startCompress(
  file.path,
  deleteOrigin: true,
);
print(info.toJson());
```
If compression is complete, a message will be displayed. You can check this
