### ISSUE TITLE
Remove videoToGif and instead add creating a short video without sound

### ISSUE THREAD

**Issue by vlada3003** [TenkaiRuri/flutter_video_compress#24]
### Description
Since Gif is lossless format, gifs made from video have are bigger in size than short videos without audio. Also, there is a problem with Regift library since it is targeting iOS 11.1. My suggestion is to remove videoToGif and add a couple of optional parameters to startCompression for creating video preview.

### Platform
Both

### Code Example (if has)
```dart
void main() {
     _flutterVideoCompress.startCompress(
          file.path,
          deleteOrigin: true,
          quality: VideoQuality.LowQuality,
          startTime: 0,
          duration: 5,
          includeAudio: false,
          frameRate: 24,
        );
}
```

### Expected solution
I will implement this by adding parameters to this method if @TenkaiRuri agrees?

**Comment by vlada3003** [comment]
I would also add additional quality parameters if that is ok with you?

**Comment by TenkaiRuri** [comment]
Regift can be solved with the below settings
```ruby
pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
      if s.name == 'Regift'
        s.swift_version = '4.0'
      end
  end
end
```

remove videoToGif will make it complicates the plugin

> I would also add additional quality parameters if that is ok with you?
I plan adding other qualities to IOS, It is convenient to solve on Android

**Comment by TenkaiRuri** [comment]
I plan to do the following things
```dart
class CustomModel {
  title: sting
}

class FlutterVideoCompress {
  _mediaInfo = {
      'title': MediaMetadataRetriever.METADATA_KEY_TITLE;
  }

  void setMediaInfoTemplate(Map<String, dynamic> custom) {
    _mediaInfo = custom;
  }

  Future<T = MediaInfo> getMediaInfo(String path) async {
    invoke(.., _mediaInfo)
  }
}

await getMediaInfo<CustomModel>(path)
```

**Comment by vlada3003** [comment]
Cool. I'll try the Regift fix. However, I don't understand what you plan to do with CustomModel? You want to switch from json to your data classes?

**Comment by TenkaiRuri** [comment]
Users can customize the data structure of MediaInfo return value and expected value

**Comment by vlada3003** [comment]
I understand, is there any performance reason why you are doing this, or you just want more structured response?

**Comment by TenkaiRuri** [comment]
Just want more structured response

**Comment by GustavoContreiras** [comment]
An option to set new aspect ratio would be nice too!

**Comment by TenkaiRuri** [comment]
@vlada3003  I suggest this should be better.

```dart
Future<MediaInfo> startCompress(
    String path, {
    VideoQuality quality = VideoQuality.DefaultQuality,
    bool deleteOrigin = false,
    bool includeAudio = false,
    int frameRate = 24,
  }) async {
}

Future<MediaInfo> cropAndCompress(
    String path, {
    VideoQuality quality = VideoQuality.DefaultQuality,
    bool deleteOrigin = false,
    bool includeAudio = false,
    int frameRate = 24,
    int startTime = 0,
    int endTime = -1,
    int duration = -1,
  }) async {
}
```

**Comment by vlada3003** [comment]
@TenkaiRuri for the cropAndCompress method, what is meant by crop part?

**Comment by TenkaiRuri** [comment]
@vlada3003  Crop video

**Comment by vlada3003** [comment]
I understand that, but crop to what?

**Comment by TenkaiRuri** [comment]
Due to my English I am very sorry, I may think too much. This enhancement is great
```dart
Future<MediaInfo> startCompress(
  String path, {
  VideoQuality quality = VideoQuality.DefaultQuality,
  bool deleteOrigin = false,
  bool includeAudio = false,
  int frameRate = 24,
  int startTime = 0,
  int endTime = -1,
  int duration = -1,
}) async {}
```
