### ISSUE TITLE
[Bug] Pod install problems with latest version

### ISSUE THREAD

**Issue by vlada3003** [TenkaiRuri/flutter_video_compress#28]
### Description
Build breaks when  use_frameworks! is added to a Podfile.
When a library that has s.static_framework = true is added to a project that has flutter_video_compress, '$pod install' fails with a message "[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (image_cropper)"
image_cropper is a library that has s.static_framework = true
if use_frameworks! isn't set then Regift won't compile.

### Platform
IOS

### Proposed solution
Is to fork Regift and to reduce the ios minimum supported version and remove the use_frameworks! flag. However, this is just a guess since I'm unfamiliar with iOS build system.

**Comment by TenkaiRuri** [comment]
Provide me the configuration of Podfile

**Comment by vlada3003** [comment]
platform :ios, '8.0'

target 'Runner' do
  use_frameworks!
  flutter_application_path = '../'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
end

pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
      if s.name == 'Regift'
        s.swift_version = '4.0'
    # elsif s.name == 'other-Plugin'
    #   s.swift_version = '5.0'
    # else
    #   s.swift_version = '4.0'
      end
  end
end

**Comment by vlada3003** [comment]
i used the same one from your setup instructions.

**Comment by vlada3003** [comment]
I have managed to make it to compile by downloading image_crop plugin and remove s.static_framework but I don't think that is the proper solution since what happens when the next static_framework is added as a flutter plugin.

**Comment by TenkaiRuri** [comment]
Podfile file look like no problem, wait me do something test

**Comment by TenkaiRuri** [comment]
I haven't encountered any problems. You can reproduce the problem on this repo to help me understand what happened [repo](https://github.com/TenkaiRuri/minimal-repo)

**Comment by TenkaiRuri** [comment]
There is also an easy way, you can run ` pod install —verbose` to tell me what happened.
