### ISSUE TITLE
The 'Pods-Runner' target has transitive dependencies that include static binaries: 

### ISSUE THREAD

**Issue by zhangruiyu** [TenkaiRuri/flutter_video_compress#35]
The 'Pods-Runner' target has transitive dependencies that include static binaries: 

![image](https://user-images.githubusercontent.com/10591822/60391915-1255f400-9b2c-11e9-9822-bd31f25e8d43.png)

**Comment by TenkaiRuri** [comment]
Would you provide the results of `flutter doctor -v`?

**Comment by zhangruiyu** [comment]
老哥 加个qq吧 有群也行 
![image](https://user-images.githubusercontent.com/10591822/60392091-0455a280-9b2f-11e9-93e8-b0a9d2a0075c.png)
