### ISSUE TITLE
[Bug]编译iOS的时候报The 'Pods-Runner' target has transitive dependencies that include statically linked binaries

### ISSUE THREAD

**Issue by goodsiwen** [TenkaiRuri/flutter_video_compress#36]
编译iOS的时候报：
    [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/siwen/MyProject/viiapp/ios/Pods/AlipaySDK-iOS/AlipaySDK.framework, /Users/siwen/MyProject/viiapp/ios/Pods/UMCAnalytics/UMAnalytics.framework, and /Users/siwen/MyProject/viiapp/ios/Pods/UMCCommon/UMCommon.framework)

请问如何解决？感谢

**Comment by TenkaiRuri** [comment]
参考中文文档中的这个部分
![image](https://user-images.githubusercontent.com/24207813/60563846-fe123100-9d8f-11e9-8dff-4268324b2ccc.png)

**Comment by goodsiwen** [comment]
又出现新的问题：
   - `Regift` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

加上：
pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
      if s.name == 'Regift'
        s.swift_version = '4.0'
    # elsif s.name == 'other-Plugin'
    #   s.swift_version = '5.0'
    # else
    #   s.swift_version = '4.0'
      end
  end
end

之后,出现连接错误：
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UMConfigure", referenced from:
      objc-class-ref in LcfarmFlutterUmengPlugin.o
  "_OBJC_CLASS_$_MobClick", referenced from:
      objc-class-ref in LcfarmFlutterUmengPlugin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

真机是arm的连接错误。

**Comment by TenkaiRuri** [comment]
hi, 你可以通过简单的注释掉关于这个插件的所有代码，然后只添加 `use_frameworks!` 测试是否会遇到这个问题。

**Comment by goodsiwen** [comment]
不用您这个压缩插件，注视掉use_frameworks，工程是可以正常运行的。

**Comment by TenkaiRuri** [comment]
所有的swift插件都会遇到这个问题，我希望您可以冷静下来看一下 [详细说明](https://www.jianshu.com/p/3a002aa5b5d6)

您注释掉了所有关于这个插件的代码之后，仅开启`use_frameworks!`报错可以证明不是由于这个插件所带来的，我希望你可以理解。

相反，你应该向报错的库提出issue，让他们能够适应目前flutter的生态，否则，以后遇到了别的swift插件也会出现同样的问题。

在前文我有提到过，迁移到objective-c才能避免这个问题，这也是我目前唯一能做的。

**Comment by TenkaiRuri** [comment]
如果你使用flutter_umengshare请把他的版本改为`^0.1.16`，我测试了它，可以正常编译。

**Comment by goodsiwen** [comment]
嗯，谢谢您，我试试

**Comment by goodsiwen** [comment]
嗯，工程现在可以正常运行了，UP主太贴心了
