### ISSUE TITLE
erro  help me

### ISSUE THREAD

**Issue by lanjiachuan** [TenkaiRuri/flutter_video_compress#5]
'flutter_video_compress/flutter_video_compress-Swift.h' file not found

**Comment by lanjiachuan** [comment]
Error output from Xcode build:
↳
    2019-04-30 16:54:51.527 xcodebuild[28265:473800] [MT] PluginLoading: Required plug-in compatibility UUID 72F7D751-F810-43B8-A53F-1F1DFD74FC54 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    2019-04-30 16:54:52.583 xcodebuild[28265:473836]  DTDeviceKit: deviceType from 4c800c98e4386c113f20fd13f312f5226034463b was NULL
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET video_player OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/lanbo/.pub-cache/hosted/pub.flutter-io.cn/flutter_video_compress-0.2.0+3/ios/Classes/FlutterVideoCompressPlugin.m:2:9: fatal error: 'flutter_video_compress/flutter_video_compress-Swift.h' file not found
    #import <flutter_video_compress/flutter_video_compress-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by TenkaiRuri** [comment]
1. Check your **ios certificate** is properly configured.
2. Using terminal to execute command of `pod install` under your {project}/ios directory
If the above checks are not working, you can provide details for me to discuss further.

**Comment by lanjiachuan** [comment]
我不知道，是否可以用中文交流？

**Comment by lanjiachuan** [comment]
Failed to build iOS app
Error output from Xcode build:
↳
    2019-05-06 00:44:17.387 xcodebuild[92499:1847846] [MT] PluginLoading: Required plug-in compatibility UUID 72F7D751-F810-43B8-A53F-1F1DFD74FC54 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET sqflite OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:149:31: warning: 'AVCapturePhotoOutput' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    @property (nonatomic, strong) AVCapturePhotoOutput *output;
                                  ^
    In module 'AVFoundation' imported from /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.h:9:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCapturePhotoOutput.h:46:12: note: 'AVCapturePhotoOutput' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface AVCapturePhotoOutput : AVCaptureOutput
               ^
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:25:12: note: annotate '' with an availability attribute to silence this warning
    @interface MTBBarcodeScanner () <AVCaptureMetadataOutputObjectsDelegate, AVCapturePhotoCaptureDelegate>
               ^
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:914:24: warning: 'AVCapturePhotoOutput' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    - (void)captureOutput:(AVCapturePhotoOutput *)captureOutput didFinishProcessingPhotoSampleBuffer:(CMSampleBufferRef)photoSampleBuffer previewPhotoSampleBuffer:(CMSampleBufferRef)previewPhotoSampleBuffer resolvedSettings:(AVCaptureResolvedPhotoSettings *)resolvedSettings bracketSettings:(AVCaptureBracketedStillImageSettings *)bracketSettings error:(NSError *)error {
                           ^
    In module 'AVFoundation' imported from /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.h:9:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCapturePhotoOutput.h:46:12: note: 'AVCapturePhotoOutput' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface AVCapturePhotoOutput : AVCaptureOutput
               ^
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:914:1: note: annotate 'captureOutput:didFinishProcessingPhotoSampleBuffer:previewPhotoSampleBuffer:resolvedSettings:bracketSettings:error:' with an availability attribute to silence this warning
    - (void)captureOutput:(AVCapturePhotoOutput *)captureOutput didFinishProcessingPhotoSampleBuffer:(CMSampleBufferRef)photoSampleBuffer previewPhotoSampleBuffer:(CMSampleBufferRef)previewPhotoSampleBuffer resolvedSettings:(AVCaptureResolvedPhotoSettings *)resolvedSettings bracketSettings:(AVCaptureBracketedStillImageSettings *)bracketSettings error:(NSError *)error {
    ^
                                                                                                                                                                                                                                                                                                                                                                                   API_AVAILABLE(ios(10.0))
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:914:222: warning: 'AVCaptureResolvedPhotoSettings' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    - (void)captureOutput:(AVCapturePhotoOutput *)captureOutput didFinishProcessingPhotoSampleBuffer:(CMSampleBufferRef)photoSampleBuffer previewPhotoSampleBuffer:(CMSampleBufferRef)previewPhotoSampleBuffer resolvedSettings:(AVCaptureResolvedPhotoSettings *)resolvedSettings bracketSettings:(AVCaptureBracketedStillImageSettings *)bracketSettings error:(NSError *)error {
                                                                                                                                                                                                                                 ^
    In module 'AVFoundation' imported from /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.h:9:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCapturePhotoOutput.h:1174:12: note: 'AVCaptureResolvedPhotoSettings' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface AVCaptureResolvedPhotoSettings : NSObject
               ^
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:914:1: note: annotate 'captureOutput:didFinishProcessingPhotoSampleBuffer:previewPhotoSampleBuffer:resolvedSettings:bracketSettings:error:' with an availability attribute to silence this warning
    - (void)captureOutput:(AVCapturePhotoOutput *)captureOutput didFinishProcessingPhotoSampleBuffer:(CMSampleBufferRef)photoSampleBuffer previewPhotoSampleBuffer:(CMSampleBufferRef)previewPhotoSampleBuffer resolvedSettings:(AVCaptureResolvedPhotoSettings *)resolvedSettings bracketSettings:(AVCaptureBracketedStillImageSettings *)bracketSettings error:(NSError *)error {
    ^
                                                                                                                                                                                                                                                                                                                                                                                   API_AVAILABLE(ios(10.0))
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:203:52: warning: 'defaultDeviceWithDeviceType:mediaType:position:' is only available on iOS 10.0 or newer [-Wunguarded-availability]
            AVCaptureDevice *device = [AVCaptureDevice defaultDeviceWithDeviceType:AVCaptureDeviceTypeBuiltInWideAngleCamera
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'AVFoundation' imported from /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.h:9:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:509:1: note: 'defaultDeviceWithDeviceType:mediaType:position:' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    + (nullable AVCaptureDevice *)defaultDeviceWithDeviceType:(AVCaptureDeviceType)deviceType mediaType:(nullable AVMediaType)mediaType position:(AVCaptureDevicePosition)position API_AVAILABLE(ios(10.0)) API_UNAVAILABLE(macos);
    ^
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:203:52: note: enclose 'defaultDeviceWithDeviceType:mediaType:position:' in an @available check to silence this warning
            AVCaptureDevice *device = [AVCaptureDevice defaultDeviceWithDeviceType:AVCaptureDeviceTypeBuiltInWideAngleCamera
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:203:80: warning: 'AVCaptureDeviceTypeBuiltInWideAngleCamera' is only available on iOS 10.0 or newer [-Wunguarded-availability]
            AVCaptureDevice *device = [AVCaptureDevice defaultDeviceWithDeviceType:AVCaptureDeviceTypeBuiltInWideAngleCamera
                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'AVFoundation' imported from /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.h:9:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:441:38: note: 'AVCaptureDeviceTypeBuiltInWideAngleCamera' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    AVF_EXPORT AVCaptureDeviceType const AVCaptureDeviceTypeBuiltInWideAngleCamera API_AVAILABLE(ios(10.0)) API_UNAVAILABLE(macos) __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
                                         ^
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:203:80: note: enclose 'AVCaptureDeviceTypeBuiltInWideAngleCamera' in an @available check to silence this warning
            AVCaptureDevice *device = [AVCaptureDevice defaultDeviceWithDeviceType:AVCaptureDeviceTypeBuiltInWideAngleCamera
                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:542:25: warning: 'AVCapturePhotoOutput' is only available on iOS 10.0 or newer [-Wunguarded-availability]
            self.output = [[AVCapturePhotoOutput alloc] init];
                            ^~~~~~~~~~~~~~~~~~~~
    In module 'AVFoundation' imported from /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.h:9:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCapturePhotoOutput.h:46:12: note: 'AVCapturePhotoOutput' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface AVCapturePhotoOutput : AVCaptureOutput
               ^
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:542:25: note: enclose 'AVCapturePhotoOutput' in an @available check to silence this warning
            self.output = [[AVCapturePhotoOutput alloc] init];
                            ^~~~~~~~~~~~~~~~~~~~
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:568:52: warning: 'defaultDeviceWithDeviceType:mediaType:position:' is only available on iOS 10.0 or newer [-Wunguarded-availability]
            AVCaptureDevice *device = [AVCaptureDevice defaultDeviceWithDeviceType:AVCaptureDeviceTypeBuiltInWideAngleCamera
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'AVFoundation' imported from /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.h:9:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:509:1: note: 'defaultDeviceWithDeviceType:mediaType:position:' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    + (nullable AVCaptureDevice *)defaultDeviceWithDeviceType:(AVCaptureDeviceType)deviceType mediaType:(nullable AVMediaType)mediaType position:(AVCaptureDevicePosition)position API_AVAILABLE(ios(10.0)) API_UNAVAILABLE(macos);
    ^
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:568:52: note: enclose 'defaultDeviceWithDeviceType:mediaType:position:' in an @available check to silence this warning
            AVCaptureDevice *device = [AVCaptureDevice defaultDeviceWithDeviceType:AVCaptureDeviceTypeBuiltInWideAngleCamera
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:568:80: warning: 'AVCaptureDeviceTypeBuiltInWideAngleCamera' is only available on iOS 10.0 or newer [-Wunguarded-availability]
            AVCaptureDevice *device = [AVCaptureDevice defaultDeviceWithDeviceType:AVCaptureDeviceTypeBuiltInWideAngleCamera
                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'AVFoundation' imported from /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.h:9:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:441:38: note: 'AVCaptureDeviceTypeBuiltInWideAngleCamera' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    AVF_EXPORT AVCaptureDeviceType const AVCaptureDeviceTypeBuiltInWideAngleCamera API_AVAILABLE(ios(10.0)) API_UNAVAILABLE(macos) __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
                                         ^
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:568:80: note: enclose 'AVCaptureDeviceTypeBuiltInWideAngleCamera' in an @available check to silence this warning
            AVCaptureDevice *device = [AVCaptureDevice defaultDeviceWithDeviceType:AVCaptureDeviceTypeBuiltInWideAngleCamera
                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:849:9: warning: 'AVCapturePhotoSettings' is only available on iOS 10.0 or newer [-Wunguarded-availability]
            AVCapturePhotoSettings *settings = [AVCapturePhotoSettings photoSettings];
            ^~~~~~~~~~~~~~~~~~~~~~
    In module 'AVFoundation' imported from /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.h:9:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCapturePhotoOutput.h:691:12: note: 'AVCapturePhotoSettings' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface AVCapturePhotoSettings : NSObject <NSCopying>
               ^
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:849:9: note: enclose 'AVCapturePhotoSettings' in an @available check to silence this warning
            AVCapturePhotoSettings *settings = [AVCapturePhotoSettings photoSettings];
            ^~~~~~~~~~~~~~~~~~~~~~
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:849:45: warning: 'AVCapturePhotoSettings' is only available on iOS 10.0 or newer [-Wunguarded-availability]
            AVCapturePhotoSettings *settings = [AVCapturePhotoSettings photoSettings];
                                                ^~~~~~~~~~~~~~~~~~~~~~
    In module 'AVFoundation' imported from /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.h:9:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCapturePhotoOutput.h:691:12: note: 'AVCapturePhotoSettings' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface AVCapturePhotoSettings : NSObject <NSCopying>
               ^
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:849:45: note: enclose 'AVCapturePhotoSettings' in an @available check to silence this warning
            AVCapturePhotoSettings *settings = [AVCapturePhotoSettings photoSettings];
                                                ^~~~~~~~~~~~~~~~~~~~~~
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:919:42: warning: 'JPEGPhotoDataRepresentationForJPEGSampleBuffer:previewPhotoSampleBuffer:' is only available on iOS 10.0 or newer [-Wunguarded-availability]
        NSData *data = [AVCapturePhotoOutput JPEGPhotoDataRepresentationForJPEGSampleBuffer:photoSampleBuffer previewPhotoSampleBuffer:previewPhotoSampleBuffer];
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'AVFoundation' imported from /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.h:9:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCapturePhotoOutput.h:423:1: note: 'JPEGPhotoDataRepresentationForJPEGSampleBuffer:previewPhotoSampleBuffer:' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    + (nullable NSData *)JPEGPhotoDataRepresentationForJPEGSampleBuffer:(CMSampleBufferRef)JPEGSampleBuffer previewPhotoSampleBuffer:(nullable CMSampleBufferRef)previewPhotoSampleBuffer API_DEPRECATED("Use -[AVCapturePhoto fileDataRepresentation] instead.", ios(10.0, 11.0));
    ^
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:919:42: note: enclose 'JPEGPhotoDataRepresentationForJPEGSampleBuffer:previewPhotoSampleBuffer:' in an @available check to silence this warning
        NSData *data = [AVCapturePhotoOutput JPEGPhotoDataRepresentationForJPEGSampleBuffer:photoSampleBuffer previewPhotoSampleBuffer:previewPhotoSampleBuffer];
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:919:21: warning: 'AVCapturePhotoOutput' is only available on iOS 10.0 or newer [-Wunguarded-availability]
        NSData *data = [AVCapturePhotoOutput JPEGPhotoDataRepresentationForJPEGSampleBuffer:photoSampleBuffer previewPhotoSampleBuffer:previewPhotoSampleBuffer];
                        ^~~~~~~~~~~~~~~~~~~~
    In module 'AVFoundation' imported from /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.h:9:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCapturePhotoOutput.h:46:12: note: 'AVCapturePhotoOutput' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface AVCapturePhotoOutput : AVCaptureOutput
               ^
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m:919:21: note: enclose 'AVCapturePhotoOutput' in an @available check to silence this warning
        NSData *data = [AVCapturePhotoOutput JPEGPhotoDataRepresentationForJPEGSampleBuffer:photoSampleBuffer previewPhotoSampleBuffer:previewPhotoSampleBuffer];
                        ^~~~~~~~~~~~~~~~~~~~
    12 warnings generated.
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: warning: 'sqlite3_wal_checkpoint_v2' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'SQLite3' imported from /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/FMDB/src/fmdb/FMDatabase.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/usr/include/sqlite3.h:8245:16: note: 'sqlite3_wal_checkpoint_v2' has been marked as being introduced in iOS 5.0 here, but the deployment target is iOS 4.3.0
    SQLITE_API int sqlite3_wal_checkpoint_v2(
                   ^
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: note: enclose 'sqlite3_wal_checkpoint_v2' in an @available check to silence this warning
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: warning: 'dispatch_queue_set_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/usr/include/dispatch/queue.h:1352:1: note: 'dispatch_queue_set_specific' has been marked as being introduced in iOS 5.0 here, but the deployment target is iOS 4.3.0
    dispatch_queue_set_specific(dispatch_queue_t queue, const void *key,
    ^
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: note: enclose 'dispatch_queue_set_specific' in an @available check to silence this warning
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: warning: 'dispatch_get_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                         ^~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/usr/include/dispatch/queue.h:1408:1: note: 'dispatch_get_specific' has been marked as being introduced in iOS 5.0 here, but the deployment target is iOS 4.3.0
    dispatch_get_specific(const void *key);
    ^
    /Users/lanbo/Desktop/workspace/AndroidStudioProjects/lan_message/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: note: enclose 'dispatch_get_specific' in an @available check to silence this warning
        FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                         ^~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    === BUILD TARGET barcode_scan OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/lanbo/.pub-cache/hosted/pub.flutter-io.cn/flutter_video_compress-0.2.0+3/ios/Classes/FlutterVideoCompressPlugin.m:2:9: fatal error: 'flutter_video_compress/flutter_video_compress-Swift.h' file not found
    #import <flutter_video_compress/flutter_video_compress-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/lanbo/.pub-cache/hosted/pub.flutter-io.cn/barcode_scan-1.0.0/ios/Classes/BarcodeScanPlugin.m:1:
    /Users/lanbo/.pub-cache/hosted/pub.flutter-io.cn/barcode_scan-1.0.0/ios/Classes/BarcodeScanPlugin.h:12:1: warning: retain'ed block property does not copy the block - use copy attribute instead [-Wobjc-noncopy-retain-block-property]
    @property(nonatomic, retain) FlutterResult result;
    ^
    1 warning generated.
    /Users/lanbo/.pub-cache/hosted/pub.flutter-io.cn/barcode_scan-1.0.0/ios/Classes/BarcodeScannerViewController.m:10:17: warning: method definition for 'initWithOptions:' not found [-Wincomplete-implementation]
    @implementation BarcodeScannerViewController {
                    ^
    In file included from /Users/lanbo/.pub-cache/hosted/pub.flutter-io.cn/barcode_scan-1.0.0/ios/Classes/BarcodeScannerViewController.m:5:
    /Users/lanbo/.pub-cache/hosted/pub.flutter-io.cn/barcode_scan-1.0.0/ios/Classes/BarcodeScannerViewController.h:19:3: note: method 'initWithOptions:' declared here
      -(id) initWithOptions:(NSDictionary *) options;
      ^
    1 warning generated.

**Comment by TenkaiRuri** [comment]
This looks like the MTBBarcodeScanner library requires target ios 10, but you set the target ios 8.
reference [How do I acquire SDKs to build target pre-8.0 iOS?](https://apple.stackexchange.com/questions/147028/how-do-i-acquire-sdks-to-build-target-pre-8-0-ios)

**Comment by lanjiachuan** [comment]
If I don't use your plugin, the app can be installed and previewed properly, but after relying on your plugin, I get an error.
=== BUILD TARGET video_player OF PROJECT Pods WITH CONFIGURATION Debug ===
/Users/lanbo/.pub-cache/hosted/pub.flutter-io.cn/flutter_video_compress-0.2.0+3/ios/Classes/FlutterVideoCompressPlugin.m:2:9: fatal error: 'flutter_video_compress/flutter_video_compress-Swift.h' file not found
#import <flutter_video_compress/flutter_video_compress-Swift.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Is this file automatically generated?

**Comment by TenkaiRuri** [comment]
Because this plugin is written by swift, You need adding `use_frameworks!` to your Podfile.
I have passed the test in a blank project.
If you have other problems, please open this issue again, thank you.
