### ISSUE TITLE
Compression progress

### ISSUE THREAD

**Issue by febg11** [TenkaiRuri/flutter_video_compress#6]
A callback that states the progress of the compression. I think ffmpeg has one built into their library but I'm not sure if that's what your using.

**Comment by TenkaiRuri** [comment]
I will update it in the next release.

**Comment by TenkaiRuri** [comment]
This feature has been implemented, you can try it now. 🎉🎉🎉
If you have any questions, you can reopen it.
Thank you for the great issue.

Amami Ruri.

**Comment by TenkaiRuri** [comment]
@febg11  If you use him, I hope you can give feedback. Thx.

**Comment by febg11** [comment]
Hi Ruri, its working great :) Thank you so much for adding it. I do have a question about my implementation. I have been using a singleton that handles  image and video compression as well as having helper methods.

My original way of using the callback was to set up a subscription in my compress function and clear it as  when compression finished/cancelled. 
However after two compression's I got Bad state: Stream has already been listened to, which i think may be whats cause the other issue  #15. 

Also if I do not unsubscribe from the stream (as there is no dispose override in my singleton) could this lead to performance problems?

**Comment by TenkaiRuri** [comment]
about #15 When the flutter video compress Initialization, will take from the cache. now it fix.

if you not unsubscribe stream I think it may cause a memory leak after many initializations, But singleton may not.
