### ISSUE TITLE
Compression hangs 

### ISSUE THREAD

**Issue by jawadt1** [TenkaiRuri/flutter_video_compress#7]
Hi 
Im having trouble getting a video to compress after I have already compressed one. I compress one video and it works fine but the second seems to hang and  never returns from the await. I'm doing it like this

final String newPath = await _flutterVideoCompress.compressVideo(path: file.path, deleteOrigin: true);

Would you please be able to help me 

Thanks 
Jawad

**Comment by lanjiachuan** [comment]
Hello, may I ask if this plugin has been run under ios, why do I say less files when I run?

**Comment by jawadt1** [comment]
Im running this on android using flutter but not sure what you mean by "why do I say less files when I run?"

**Comment by lanjiachuan** [comment]
Working fine on Android, but compiling error when using ios system,

 Error output from Xcode build:
2019-04-30 16:54:51.527 xcodebuild[28265:473800] [MT] PluginLoading: Required plug-in compatibility UUID 72F7D751-F810-43B8-A53F-1F1DFD74FC54 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2019-04-30 16:54:52.583 xcodebuild[28265:473836] DTDeviceKit: deviceType from 4c800c98e4386c113f20fd13f312f5226034463b was NULL
** BUILD FAILED **

Xcode's output:
↳
=== BUILD TARGET video_player OF PROJECT Pods WITH CONFIGURATION Debug ===
/Users/lanbo/.pub-cache/hosted/pub.flutter-io.cn/flutter_video_compress-0.2.0+3/ios/Classes/FlutterVideoCompressPlugin.m:2:9: fatal error: 'flutter_video_compress/flutter_video_compress-Swift.h' file not found
#import <flutter_video_compress/flutter_video_compress-Swift.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by jawadt1** [comment]
wait so if you compress a video and its compressed and you compress another one straight after does it compress that one or does what mine does and just hangs on android?

**Comment by lanjiachuan** [comment]
Sorry, I didn't use this feature, so I don't know how to answer you. I only used the screenshot feature.

**Comment by jawadt1** [comment]
oh this might be a different issue might be best to start a new thread so that can be looked at as well

**Comment by TenkaiRuri** [comment]
Can you provide further information?

**Comment by febg11** [comment]
I am experiencing the same problem. I choose a video from the gallery, then i choose another one and it never finishes compressing.
The logs it hangs on are these 
D/FFmpeg  (14746): Build.CPU_ABI : arm64-v8a
D/FFmpeg  (14746): ffmpeg is ready!
D/FFmpeg  (14746): Running publishing updates method

 The videos aren't large, around 20mb and when i close the app and compress the same video it works.

**Comment by febg11** [comment]
Has this been fixed in a new version?
