### ISSUE TITLE
Most of the case Not Working with Gallery

### ISSUE THREAD

**Issue by PriyaParashar93** [TenkaiRuri/flutter_video_compress#9]
It is not working with WhatsApp video and sometime also with Gallery videos.

**Comment by TenkaiRuri** [comment]
Is it on the ios platform?

**Comment by PriyaParashar93** [comment]
This issue on Android platform.

**Comment by TenkaiRuri** [comment]
If you are talking about the function of compression, I think it works well. If you mean to use it, I have tested it in both apps, no problem.
![Screenshot_20190511-093245](https://user-images.githubusercontent.com/24207813/57563585-26099780-73d2-11e9-9440-f2a946e8e295.png)
![Screenshot_20190511-093251](https://user-images.githubusercontent.com/24207813/57563591-3752a400-73d2-11e9-98e4-af86725a84b2.png)
